import type { Job, TailoredResume } from "@/db/schema";

const SECTORS = [
  "Technology",
  "Healthcare",
  "Finance",
  "Energy",
  "Education",
  "Manufacturing",
  "Retail",
  "Government",
  "Consulting",
  "Media",
  "Automotive",
  "Pharmaceuticals",
  "Aerospace",
  "Telecommunications",
  "Biotechnology",
];

const COMPANIES: Record<string, string[]> = {
  Technology: [
    "Google",
    "Microsoft",
    "Apple",
    "Amazon",
    "Meta",
    "Netflix",
    "Salesforce",
    "Adobe",
    "Oracle",
    "IBM",
    "Intel",
    "NVIDIA",
    "Stripe",
    "Airbnb",
    "Uber",
  ],
  Healthcare: [
    "Johnson & Johnson",
    "UnitedHealth Group",
    "Pfizer",
    "Roche",
    "Novartis",
    "Medtronic",
    "Abbott",
    "Siemens Healthineers",
    "Philips Healthcare",
    "Teladoc Health",
    "Cerner",
    "Epic Systems",
    "HCA Healthcare",
    "Mayo Clinic",
    "Cleveland Clinic",
  ],
  Finance: [
    "JPMorgan Chase",
    "Goldman Sachs",
    "Morgan Stanley",
    "Bank of America",
    "Citigroup",
    "Wells Fargo",
    "BlackRock",
    "Berkshire Hathaway",
    "Visa",
    "Mastercard",
    "American Express",
    "HSBC",
    "Barclays",
    "Deutsche Bank",
    "UBS",
  ],
  Energy: [
    "ExxonMobil",
    "Shell",
    "BP",
    "Chevron",
    "TotalEnergies",
    "NextEra Energy",
    "Duke Energy",
    "Siemens Energy",
    "Schneider Electric",
    "Tesla Energy",
    "Orsted",
    "Equinor",
    "ConocoPhillips",
    "Enbridge",
    "Dominion Energy",
  ],
  Education: [
    "Pearson",
    "Coursera",
    "Khan Academy",
    "Duolingo",
    "Udemy",
    "2U",
    "Chegg",
    "Blackboard",
    "McGraw Hill",
    "Scholastic",
    "Harvard University",
    "MIT",
    "Stanford Online",
    "Guild Education",
    "Pluralsight",
  ],
  Manufacturing: [
    "Boeing",
    "Siemens",
    "General Electric",
    "3M",
    "Caterpillar",
    "Honeywell",
    "ABB",
    "Bosch",
    "Hyundai",
    "Toyota",
    "Procter & Gamble",
    "Unilever",
    "Cummins",
    "Emerson",
    "Rockwell Automation",
  ],
  Retail: [
    "Walmart",
    "Target",
    "Costco",
    "Home Depot",
    "Amazon Retail",
    "Best Buy",
    "IKEA",
    "Nike",
    "Adidas",
    "Zara",
    "Shopify",
    "Etsy",
    "Wayfair",
    "Lowe's",
    "Macy's",
  ],
  Government: [
    "NASA",
    "FDA",
    "EPA",
    "DARPA",
    "NIST",
    "DOE",
    "NSF",
    "US Digital Service",
    "GSA",
    "CDC",
    "USDA",
    "State Department",
    "Treasury",
    "Defense Digital Service",
    "CISA",
  ],
  Consulting: [
    "McKinsey & Company",
    "Boston Consulting Group",
    "Bain & Company",
    "Deloitte",
    "Accenture",
    "KPMG",
    "PwC",
    "EY",
    "Capgemini",
    "Tata Consultancy",
    "Infosys",
    "Wipro",
    "Cognizant",
    "Slalom",
    "Booz Allen Hamilton",
  ],
  Media: [
    "Disney",
    "Warner Bros",
    "Netflix Studios",
    "Spotify",
    "Sony Pictures",
    "NBCUniversal",
    "Paramount",
    "BBC",
    "The New York Times",
    "Bloomberg",
    "Reuters",
    "CNN",
    "Fox Corporation",
    "Comcast",
    "Roku",
  ],
  Automotive: [
    "Tesla",
    "Ford",
    "General Motors",
    "Rivian",
    "Lucid Motors",
    "Volkswagen",
    "BMW",
    "Mercedes-Benz",
    "Toyota",
    "Honda",
    "Hyundai",
    "Porsche",
    "Volvo",
    "Ferrari",
    "Stellantis",
  ],
  Pharmaceuticals: [
    "Pfizer",
    "Novartis",
    "Roche",
    "AstraZeneca",
    "Merck",
    "Sanofi",
    "Eli Lilly",
    "AbbVie",
    "Bristol Myers Squibb",
    "GSK",
    "Johnson & Johnson",
    "Amgen",
    "Biogen",
    "Gilead Sciences",
    "Regeneron",
  ],
  Aerospace: [
    "Boeing",
    "Airbus",
    "Lockheed Martin",
    "Northrop Grumman",
    "Raytheon",
    "SpaceX",
    "Blue Origin",
    "BAE Systems",
    "General Dynamics",
    "Safran",
    "L3Harris",
    "Thales",
    "Leonardo",
    "Ball Aerospace",
    "Rocket Lab",
  ],
  Telecommunications: [
    "AT&T",
    "Verizon",
    "T-Mobile",
    "Vodafone",
    "Orange",
    "Deutsche Telekom",
    "Ericsson",
    "Nokia",
    "Cisco",
    "Huawei",
    "Qualcomm",
    "Comcast",
    "Charter",
    "Twilio",
    "ZOOM",
  ],
  Biotechnology: [
    "Moderna",
    "Illumina",
    "CRISPR Therapeutics",
    "Vertex Pharmaceuticals",
    "Seagen",
    "BioNTech",
    "Alnylam",
    "Biogen",
    "Genentech",
    "10x Genomics",
    "Pacific Biosciences",
    "Twist Bioscience",
    "Sarepta",
    "Beam Therapeutics",
    "Intellia",
  ],
};

const JOB_TITLES: Record<string, string[]> = {
  Technology: [
    "Software Engineer",
    "Senior Frontend Developer",
    "Backend Engineer",
    "Full Stack Developer",
    "ML Engineer",
    "Data Engineer",
    "DevOps Engineer",
    "Cloud Architect",
    "Security Engineer",
    "Mobile Developer",
    "Site Reliability Engineer",
    "Platform Engineer",
    "Research Scientist",
    "Product Manager",
    "Engineering Manager",
  ],
  Healthcare: [
    "Data Scientist",
    "Health Informatics Analyst",
    "Clinical Research Coordinator",
    "Biostatistician",
    "Healthcare Analyst",
    "Medical Science Liaison",
    "Quality Assurance Specialist",
    "Regulatory Affairs Manager",
    "Health IT Consultant",
    "Research Scientist",
    "Bioinformatics Engineer",
    "Clinical Data Manager",
    "Epidemiologist",
    "Public Health Analyst",
    "Health Policy Researcher",
  ],
  Finance: [
    "Quantitative Analyst",
    "Risk Manager",
    "Financial Analyst",
    "Data Scientist",
    "Investment Analyst",
    "Portfolio Manager",
    "Fintech Engineer",
    "Compliance Officer",
    "Actuarial Analyst",
    "Trading Strategist",
    "Credit Analyst",
    "Treasury Analyst",
    "Economic Researcher",
    "Blockchain Developer",
    "Fraud Detection Specialist",
  ],
  Energy: [
    "Renewable Energy Engineer",
    "Grid Systems Analyst",
    "Energy Data Scientist",
    "Sustainability Consultant",
    "Power Systems Engineer",
    "Environmental Engineer",
    "Energy Efficiency Analyst",
    "Project Manager",
    "Operations Research Analyst",
    "Carbon Markets Analyst",
    "Geospatial Analyst",
    "Battery Systems Engineer",
    "Smart Grid Developer",
    "Climate Risk Analyst",
    "Energy Economist",
  ],
  Education: [
    "Instructional Designer",
    "Learning Engineer",
    "EdTech Product Manager",
    "Curriculum Developer",
    "Data Analyst",
    "UX Researcher",
    "Content Strategist",
    "Platform Engineer",
    "AI Education Specialist",
    "Assessment Scientist",
    "Learning Analytics Engineer",
    "Accessibility Specialist",
    "User Researcher",
    "Growth Analyst",
    "Program Manager",
  ],
  Manufacturing: [
    "Industrial Engineer",
    "Quality Engineer",
    "Process Engineer",
    "Automation Engineer",
    "Supply Chain Analyst",
    "Operations Manager",
    "Data Analyst",
    "Systems Engineer",
    "Lean Manufacturing Specialist",
    "Robotics Engineer",
    "Production Planner",
    "Reliability Engineer",
    "Sustainability Analyst",
    "Digital Manufacturing Lead",
    "Plant Manager",
  ],
  Retail: [
    "Data Scientist",
    "Supply Chain Analyst",
    "Pricing Analyst",
    "E-commerce Manager",
    "Demand Planner",
    "Customer Insights Analyst",
    "Merchandising Analyst",
    "Personalization Engineer",
    "Inventory Optimization Analyst",
    "Digital Marketing Analyst",
    "Store Operations Analyst",
    "Logistics Coordinator",
    "Vendor Manager",
    "Product Analyst",
    "Retail Strategy Consultant",
  ],
  Government: [
    "Policy Analyst",
    "Data Scientist",
    "Research Scientist",
    "Program Analyst",
    "Systems Administrator",
    "Cybersecurity Specialist",
    "Intelligence Analyst",
    "Grant Program Manager",
    "Digital Services Specialist",
    "Public Affairs Specialist",
    "Data Engineer",
    "Cloud Architect",
    "Scientific Programmer",
    "Operations Research Analyst",
    "Legislative Analyst",
  ],
  Consulting: [
    "Management Consultant",
    "Data Scientist",
    "Strategy Analyst",
    "Technology Consultant",
    "Business Analyst",
    "Digital Transformation Lead",
    "Risk Advisory Consultant",
    "Operations Consultant",
    "Analytics Manager",
    "Change Management Specialist",
    "Financial Advisory Analyst",
    "IT Consultant",
    "Healthcare Consultant",
    "Sustainability Consultant",
    "AI Strategy Consultant",
  ],
  Media: [
    "Data Scientist",
    "Content Strategist",
    "Product Manager",
    "Audience Insights Analyst",
    "Streaming Engineer",
    "Ad Tech Engineer",
    "Personalization Engineer",
    "Video Platform Engineer",
    "Media Planner",
    "Social Media Analyst",
    "SEO Analyst",
    "Growth Analyst",
    "Recommendation Engineer",
    "Content Operations Manager",
    "Digital Producer",
  ],
  Automotive: [
    "Mechanical Engineer",
    "Electrical Engineer",
    "Battery Engineer",
    "ADAS Engineer",
    "Quality Engineer",
    "Manufacturing Engineer",
    "Supply Chain Analyst",
    "Simulation Engineer",
    "Software Engineer",
    "Data Analyst",
    "Test Engineer",
    "Thermal Engineer",
    "Materials Engineer",
    "Systems Engineer",
    "Product Planner",
  ],
  Pharmaceuticals: [
    "Research Scientist",
    "Clinical Trial Manager",
    "Regulatory Affairs Specialist",
    "Formulation Scientist",
    "Quality Control Analyst",
    "Pharmacovigilance Specialist",
    "Medical Affairs Manager",
    "Data Scientist",
    "Process Development Scientist",
    "Analytical Chemist",
    "Drug Safety Associate",
    "Biostatistician",
    "Manufacturing Scientist",
    "HEOR Analyst",
    "Validation Engineer",
  ],
  Aerospace: [
    "Aerospace Engineer",
    "Systems Engineer",
    "Propulsion Engineer",
    "Flight Dynamics Analyst",
    "GNC Engineer",
    "Structural Analyst",
    "Avionics Engineer",
    "Thermal Engineer",
    "Mission Operations Analyst",
    "Orbital Mechanic",
    "Software Engineer",
    "Test Engineer",
    "Manufacturing Engineer",
    "Payload Engineer",
    "Spacecraft Systems Analyst",
  ],
  Telecommunications: [
    "Network Engineer",
    "RF Engineer",
    "5G Systems Engineer",
    "Data Scientist",
    "Cloud Infrastructure Engineer",
    "Solutions Architect",
    "NOC Engineer",
    "Product Manager",
    "Business Intelligence Analyst",
    "VoIP Engineer",
    "Wireless Protocol Engineer",
    "Optimization Engineer",
    "Cybersecurity Analyst",
    "Technical Program Manager",
    "Systems Analyst",
  ],
  Biotechnology: [
    "Research Scientist",
    "Computational Biologist",
    "Process Development Engineer",
    "Assay Development Scientist",
    "Gene Therapy Scientist",
    "Protein Engineer",
    "NGS Data Analyst",
    "QA Validation Specialist",
    "Manufacturing Associate",
    "Clinical Scientist",
    "Bioinformatics Scientist",
    "Cell Culture Scientist",
    "Downstream Process Engineer",
    "Upstream Process Engineer",
    "Regulatory CMC Manager",
  ],
};

const HIGHLIGHT_TEMPLATES: Record<string, string[]> = {
  Technology: [
    "Emphasized system design and scalability experience",
    "Reordered skills to prioritize cloud infrastructure and distributed systems",
    "Highlighted open-source contributions and technical leadership",
    "Tailored project descriptions to include CI/CD and DevOps practices",
    "Refined summary to emphasize full-stack architecture expertise",
    "Added machine learning pipeline experience for ML roles",
    "Featured React/TypeScript depth for frontend positions",
    "Showcased API design and microservices architecture",
  ],
  Healthcare: [
    "Highlighted clinical data analysis and patient outcomes research",
    "Reordered skills to prioritize HL7/FHIR and medical informatics",
    "Emphasized regulatory compliance (HIPAA, FDA) knowledge",
    "Tailored summary to bridge healthcare domain with technical skills",
    "Featured experience with EHR systems and clinical workflows",
    "Added biostatistics and epidemiological methods expertise",
    "Showcased healthcare AI and diagnostic imaging experience",
    "Refined experience bullets to include patient-centric outcomes",
  ],
  Finance: [
    "Reordered skills to prioritize quantitative modeling and risk analysis",
    "Highlighted fintech and blockchain development experience",
    "Emphasized regulatory compliance (SOX, Basel III) expertise",
    "Tailored summary to stress data-driven financial decision making",
    "Added algorithmic trading and portfolio optimization details",
    "Featured SQL and financial data pipeline experience",
    "Showcased Python/R expertise for quantitative research",
    "Refined bullets to include fraud detection and AML concepts",
  ],
  Energy: [
    "Highlighted renewable energy and sustainability expertise",
    "Reordered skills to prioritize power systems and grid analysis",
    "Emphasized environmental modeling and carbon analysis",
    "Tailored summary for clean energy transition focus",
    "Added experience with energy storage and battery systems",
    "Featured data analytics for smart grid applications",
    "Showcased project management for infrastructure projects",
    "Refined bullets to include regulatory and policy knowledge",
  ],
  Education: [
    "Highlighted instructional design and learning science expertise",
    "Reordered skills to prioritize edtech platform development",
    "Emphasized data-driven approach to learning outcomes",
    "Tailored summary to bridge pedagogy with technology",
    "Added accessibility and inclusive design experience",
    "Featured curriculum development and assessment design",
    "Showcased user research and UX for learning products",
    "Refined bullets to include AI-powered tutoring experience",
  ],
  Manufacturing: [
    "Highlighted lean manufacturing and Six Sigma expertise",
    "Reordered skills to prioritize automation and robotics",
    "Emphasized supply chain optimization experience",
    "Tailored summary for Industry 4.0 and smart manufacturing",
    "Added IoT and sensor data analytics experience",
    "Featured quality control and continuous improvement",
    "Showcased ERP systems and production planning expertise",
    "Refined bullets to include predictive maintenance knowledge",
  ],
  Retail: [
    "Highlighted demand forecasting and inventory optimization",
    "Reordered skills to prioritize e-commerce and personalization",
    "Emphasized customer analytics and segmentation experience",
    "Tailored summary for omnichannel retail strategy",
    "Added supply chain and logistics analytics expertise",
    "Featured A/B testing and growth experimentation",
    "Showcased pricing optimization and promotion analysis",
    "Refined bullets to include last-mile delivery experience",
  ],
  Government: [
    "Highlighted policy analysis and program evaluation expertise",
    "Reordered skills to prioritize cybersecurity and data protection",
    "Emphasized public sector stakeholder management",
    "Tailored summary for public service and mission-driven work",
    "Added classified systems and security clearance details",
    "Featured grant writing and funding proposal experience",
    "Showcased open data and transparency initiative work",
    "Refined bullets to include regulatory compliance knowledge",
  ],
  Consulting: [
    "Highlighted client engagement and stakeholder management",
    "Reordered skills to prioritize problem-solving frameworks",
    "Emphasized cross-functional team leadership",
    "Tailored summary for strategic advisory and transformation",
    "Added industry-specific expertise relevant to target practice",
    "Featured data storytelling and executive presentation skills",
    "Showcased project delivery in fast-paced environments",
    "Refined bullets to include digital transformation experience",
  ],
  Media: [
    "Highlighted content strategy and audience development",
    "Reordered skills to prioritize streaming and ad tech",
    "Emphasized data-driven content recommendation expertise",
    "Tailored summary for digital media transformation",
    "Added real-time analytics and event streaming experience",
    "Featured A/B testing and engagement optimization",
    "Showcased video platform and CDN technology knowledge",
    "Refined bullets to include monetization and yield management",
  ],
  Automotive: [
    "Highlighted EV and battery technology expertise",
    "Reordered skills to prioritize ADAS and autonomous systems",
    "Emphasized embedded systems and real-time programming",
    "Tailored summary for software-defined vehicle focus",
    "Added simulation and digital twin experience",
    "Featured functional safety (ISO 26262) knowledge",
    "Showcased cross-functional collaboration with hardware teams",
    "Refined bullets to include sustainability and lightweight design",
  ],
  Pharmaceuticals: [
    "Highlighted drug development and clinical trial expertise",
    "Reordered skills to prioritize regulatory and quality systems",
    "Emphasized CMC and process development experience",
    "Tailored summary for patient-centric R&D focus",
    "Added statistical analysis and DOE knowledge",
    "Featured cross-functional collaboration with medical affairs",
    "Showcased GMP/GLP compliance and validation experience",
    "Refined bullets to include pharmacovigilance awareness",
  ],
  Aerospace: [
    "Highlighted spacecraft systems and mission design expertise",
    "Reordered skills to prioritize GNC and orbital mechanics",
    "Emphasized model-based systems engineering (MBSE)",
    "Tailored summary for NewSpace and commercial space focus",
    "Added multi-physics simulation and analysis experience",
    "Featured safety-critical software development knowledge",
    "Showcased interdisciplinary team collaboration",
    "Refined bullets to include propulsion and thermal analysis",
  ],
  Telecommunications: [
    "Highlighted 5G and wireless protocol expertise",
    "Reordered skills to prioritize network virtualization and SDN",
    "Emphasized VoIP and real-time communications experience",
    "Tailored summary for next-gen network architecture",
    "Added network analytics and optimization experience",
    "Featured cloud-native telecom (CNF) expertise",
    "Showcashed NFV and edge computing knowledge",
    "Refined bullets to include spectrum analysis experience",
  ],
  Biotechnology: [
    "Highlighted gene therapy and molecular biology expertise",
    "Reordered skills to prioritize NGS and bioinformatics",
    "Emphasized cell culture and process development",
    "Tailored summary for precision medicine focus",
    "Added computational biology and pipeline development",
    "Featured CMC and regulatory strategy knowledge",
    "Showcased assay development and validation experience",
    "Refined bullets to include quality and compliance expertise",
  ],
};

const CHANGE_TEMPLATES: Record<string, string[]> = {
  Technology: [
    "Summary restructured to emphasize system architecture and technical leadership",
    "Skills section reordered: React, TypeScript, Node.js, AWS, Kubernetes prioritized",
    "Added cloud infrastructure and DevOps achievements to experience section",
    "Project descriptions reframed with 'scalability', 'performance', and 'reliability' keywords",
    "Education section moved below experience (industry standard for senior tech roles)",
    "Added relevant certifications section with AWS Solutions Architect and CKA",
    "Technical skills grouped by Frontend, Backend, Cloud, and Tools categories",
    "Experience bullets rewritten to use STAR methodology with metrics",
  ],
  Healthcare: [
    "Summary restructured to bridge clinical domain expertise with technical skills",
    "Skills section reordered: HL7, FHIR, SQL, Python, Data Visualization prioritized",
    "Added clinical data analysis projects with patient outcomes metrics",
    "Project descriptions reframed with 'patient care', 'compliance', and 'interoperability' keywords",
    "Relevant coursework in Biostatistics and Epidemiology added to education",
    "HIPAA compliance and regulatory knowledge highlighted prominently",
    "Added experience with EHR systems (Epic, Cerner) to technical skills",
    "Experience bullets rewritten to emphasize clinical impact and safety",
  ],
  Finance: [
    "Summary restructured to emphasize quantitative analysis and risk management",
    "Skills section reordered: Python, R, SQL, Bloomberg Terminal, Excel VBA prioritized",
    "Added financial modeling and portfolio optimization project details",
    "Project descriptions reframed with 'risk-adjusted returns', 'alpha generation', and 'backtesting' keywords",
    "CFA Level I and relevant certifications prominently displayed",
    "Experience bullets rewritten to include specific financial metrics and AUM figures",
    "Added algorithmic trading system experience to technical section",
    "Regulatory compliance (SOX, Dodd-Frank) knowledge emphasized",
  ],
  Energy: [
    "Summary restructured to emphasize sustainability and renewable energy focus",
    "Skills section reordered: MATLAB, Python, Power Systems, Energy Modeling prioritized",
    "Added renewable energy project experience with capacity and efficiency metrics",
    "Project descriptions reframed with 'carbon reduction', 'grid integration', and 'LCOE' keywords",
    "Relevant certifications (LEED, PE license progress) added to education section",
    "Experience bullets rewritten to include specific energy and environmental metrics",
    "Added knowledge of FERC regulations and energy market structures",
    "GIS and geospatial analysis tools highlighted for site assessment roles",
  ],
  Education: [
    "Summary restructured to emphasize learning science and instructional technology",
    "Skills section reordered: Instructional Design, LMS, Python, Data Analytics prioritized",
    "Added curriculum development and learning outcome measurement examples",
    "Project descriptions reframed with ' learner engagement', 'completion rates', and 'mastery' keywords",
    "Teaching and tutoring experience highlighted in dedicated section",
    "EdTech platform experience (Canvas, Blackboard, Moodle) added to skills",
    "Experience bullets rewritten to include learning metrics and student outcomes",
    "Accessibility and Universal Design for Learning (UDL) principles emphasized",
  ],
  Manufacturing: [
    "Summary restructured to emphasize operational excellence and automation",
    "Skills section reordered: Six Sigma, AutoCAD, PLC, Python, MES prioritized",
    "Added process improvement projects with cost savings and efficiency metrics",
    "Project descriptions reframed with 'OEE', 'throughput', and 'quality' keywords",
    "Lean Six Sigma Green Belt certification prominently displayed",
    "Experience bullets rewritten to include specific production and quality metrics",
    "Added knowledge of ISO 9001 and ISO 14001 standards",
    "ERP systems (SAP, Oracle) experience highlighted in technical skills",
  ],
  Retail: [
    "Summary restructured to emphasize customer analytics and omnichannel strategy",
    "Skills section reordered: SQL, Python, Tableau, A/B Testing, Forecasting prioritized",
    "Added demand forecasting and inventory optimization examples with accuracy metrics",
    "Project descriptions reframed with 'conversion', 'basket size', and 'customer lifetime value' keywords",
    "Experience bullets rewritten to include specific revenue and efficiency metrics",
    "Added e-commerce platform experience (Shopify, Magento) to technical skills",
    "Customer segmentation and personalization projects highlighted",
    "Supply chain and vendor management experience emphasized",
  ],
  Government: [
    "Summary restructured to emphasize public service and mission-driven outcomes",
    "Skills section reordered: Policy Analysis, Data Visualization, Python, GIS prioritized",
    "Added program evaluation and policy impact assessment examples",
    "Project descriptions reframed with 'public benefit', 'stakeholder engagement', and 'transparency' keywords",
    "Security clearance level and eligibility prominently noted",
    "Experience bullets rewritten to emphasize public impact and efficiency gains",
    "Added knowledge of federal acquisition regulations (FAR) where relevant",
    "Open data and civic tech project experience highlighted",
  ],
  Consulting: [
    "Summary restructured to emphasize problem-solving and client impact",
    "Skills section reordered: Strategy Frameworks, Excel, Python, Tableau, SQL prioritized",
    "Added case study examples with quantified client outcomes",
    "Project descriptions reframed with 'stakeholder alignment', 'change management', and 'ROI' keywords",
    "Experience bullets rewritten to include specific revenue and efficiency impacts",
    "Industry expertise areas highlighted in a dedicated section",
    "Client presentation and executive communication skills emphasized",
    "Added relevant frameworks (McKinsey 7S, BCG Matrix, etc.) knowledge",
  ],
  Media: [
    "Summary restructured to emphasize audience growth and content innovation",
    "Skills section reordered: Content Strategy, Analytics, Python, Video Editing prioritized",
    "Added content performance analysis with engagement and reach metrics",
    "Project descriptions reframed with 'audience engagement', 'monetization', and 'retention' keywords",
    "Experience bullets rewritten to include viewership and revenue metrics",
    "Added streaming platform and CMS experience to technical skills",
    "A/B testing and recommendation system experience highlighted",
    "Ad tech and programmatic advertising knowledge added",
  ],
  Automotive: [
    "Summary restructured to emphasize EV technology and software-defined vehicles",
    "Skills section reordered: MATLAB, Embedded C, Python, CAN, AUTOSAR prioritized",
    "Added vehicle-level testing and validation experience with specific metrics",
    "Project descriptions reframed with 'range optimization', 'safety', and 'OTA' keywords",
    "Experience bullets rewritten to include specific performance and efficiency metrics",
    "Added functional safety (ISO 26262) and ASPICE knowledge",
    "Hardware-in-the-loop (HIL) and simulation experience highlighted",
    "Battery management system (BMS) expertise added for EV roles",
  ],
  Pharmaceuticals: [
    "Summary restructured to emphasize drug development and regulatory strategy",
    "Skills section reordered: GMP, HPLC, Statistical Analysis, R, SQL prioritized",
    "Added CMC and formulation development experience with phase-appropriate examples",
    "Project descriptions reframed with 'purity', 'yield', and 'regulatory compliance' keywords",
    "Experience bullets rewritten to include specific analytical and quality metrics",
    "Added ICH guidelines and FDA/EMA regulatory knowledge",
    "Method validation and transfer experience highlighted prominently",
    "Cross-functional collaboration with clinical and commercial teams emphasized",
  ],
  Aerospace: [
    "Summary restructured to emphasize spacecraft systems and mission operations",
    "Skills section reordered: STK, MATLAB, C++, Systems Engineering, DOORS prioritized",
    "Added mission design and analysis experience with specific orbital parameters",
    "Project descriptions reframed with 'mission success', 'margin', and 'heritage' keywords",
    "Experience bullets rewritten to include specific mission and system performance metrics",
    "Added model-based systems engineering (MBSE) and SysML knowledge",
    "Environmental testing (TVAC, vibration, EMI) experience highlighted",
    "Flight software development and FDIR expertise added",
  ],
  Telecommunications: [
    "Summary restructured to emphasize next-gen network architecture and 5G",
    "Skills section reordered: 5G NR, Python, Network Simulation, Cloud-Native prioritized",
    "Added network performance optimization experience with KPI improvements",
    "Project descriptions reframed with 'latency reduction', 'capacity', and 'coverage' keywords",
    "Experience bullets rewritten to include specific network performance metrics",
    "Added cloud-native network function (CNF) and Kubernetes knowledge",
    "RF planning and spectrum analysis experience highlighted",
    "VoIP and real-time communications protocol expertise added",
  ],
  Biotechnology: [
    "Summary restructured to emphasize gene therapy and cell engineering",
    "Skills section reordered: Cell Culture, NGS, CRISPR, Python, Bioprocessing prioritized",
    "Added process development and scale-up experience with titer/yield metrics",
    "Project descriptions reframed with 'potency', 'purity', and 'CQAs' keywords",
    "Experience bullets rewritten to include specific analytical and process metrics",
    "Added regulatory CMC writing and filing strategy knowledge",
    "DOE and statistical process control experience highlighted",
    "Cell line development and clone selection expertise added",
  ],
};

const KEYWORDS: Record<string, string[]> = {
  Technology: [
    "React",
    "TypeScript",
    "Node.js",
    "AWS",
    "Kubernetes",
    "Docker",
    "Python",
    "GraphQL",
    "PostgreSQL",
    "Redis",
    "Microservices",
    "CI/CD",
    "Terraform",
    "Go",
    "Rust",
  ],
  Healthcare: [
    "HL7",
    "FHIR",
    "HIPAA",
    "Python",
    "R",
    "SQL",
    "Machine Learning",
    "Data Visualization",
    "Clinical Data",
    "EHR",
    "Biostatistics",
    "Epidemiology",
    "Healthcare AI",
    "OMOP",
    "Patient Safety",
  ],
  Finance: [
    "Python",
    "R",
    "SQL",
    "Bloomberg",
    "Excel VBA",
    "Risk Modeling",
    "Monte Carlo",
    "Portfolio Theory",
    "Derivatives",
    "Fixed Income",
    "Quantitative Analysis",
    "Machine Learning",
    "Time Series",
    "Stata",
    "Blockchain",
  ],
  Energy: [
    "MATLAB",
    "Python",
    "Power Systems",
    "Energy Modeling",
    "GIS",
    "HOMER",
    "PVsyst",
    "Grid Analysis",
    "LCOE",
    "Carbon Markets",
    "Smart Grid",
    "Battery Systems",
    "SCADA",
    "ETAP",
    "RETScreen",
  ],
  Education: [
    "Instructional Design",
    "LMS",
    "Python",
    "Learning Analytics",
    "Curriculum Dev",
    "Assessment Design",
    "Accessibility",
    "UX Research",
    "Data Analysis",
    "EdTech",
    "Gamification",
    "SCORM",
    "xAPI",
    "Universal Design",
    "AI Tutoring",
  ],
  Manufacturing: [
    "Six Sigma",
    "AutoCAD",
    "PLC",
    "Python",
    "MES",
    "SAP",
    "Lean Manufacturing",
    "IoT",
    "Predictive Maintenance",
    "Robotics",
    "SolidWorks",
    "OEE",
    "Quality Systems",
    "Automation",
    "SPC",
  ],
  Retail: [
    "SQL",
    "Python",
    "Tableau",
    "A/B Testing",
    "Demand Forecasting",
    "Inventory Optimization",
    "Personalization",
    "Customer Analytics",
    "RFM Analysis",
    "Pricing Strategy",
    "Omnichannel",
    "Supply Chain",
    "Looker",
    "Google Analytics",
    "Attribution Modeling",
  ],
  Government: [
    "Policy Analysis",
    "Data Visualization",
    "Python",
    "GIS",
    "Program Evaluation",
    "Stakeholder Mgmt",
    "Risk Assessment",
    "Cybersecurity",
    "Grant Writing",
    "Budget Analysis",
    "Open Data",
    "Regulatory Analysis",
    "Public Health",
    "Emergency Mgmt",
    "Strategic Planning",
  ],
  Consulting: [
    "Strategy Frameworks",
    "Excel",
    "Python",
    "Tableau",
    "SQL",
    "Client Management",
    "Change Management",
    "Market Analysis",
    "Financial Modeling",
    "Stakeholder Analysis",
    "Agile",
    "Benchmarking",
    "Data Storytelling",
    "Executive Presentations",
    "ROI Analysis",
  ],
  Media: [
    "Content Strategy",
    "Analytics",
    "Python",
    "Video Editing",
    "A/B Testing",
    "Recommendation Systems",
    "Ad Tech",
    "Programmatic",
    "SEO/SEM",
    "Social Media",
    "Streaming Tech",
    "CDN",
    "Audience Dev",
    "Monetization",
    "DSP/SSP",
  ],
  Automotive: [
    "MATLAB",
    "Embedded C",
    "Python",
    "CAN",
    "AUTOSAR",
    "Simulink",
    "ISO 26262",
    "ADAS",
    "Battery Systems",
    "Vehicle Dynamics",
    "HIL Testing",
    "MBD",
    "Functional Safety",
    "Vector Tools",
    "OTA Systems",
  ],
  Pharmaceuticals: [
    "GMP",
    "HPLC",
    "Statistical Analysis",
    "R",
    "SQL",
    "Method Validation",
    "CMC",
    "Formulation",
    "Quality Control",
    "ICH Guidelines",
    "DOE",
    "Regulatory Writing",
    "Process Dev",
    "Stability",
    "Analytical Chemistry",
  ],
  Aerospace: [
    "STK",
    "MATLAB",
    "C++",
    "Systems Engineering",
    "DOORS",
    "Orbital Mechanics",
    "GNC",
    "MBSE",
    "SysML",
    "Flight Software",
    "Propulsion",
    "Thermal Analysis",
    "FDIR",
    "Mission Design",
    "CFD",
  ],
  Telecommunications: [
    "5G NR",
    "Python",
    "Network Simulation",
    "Cloud-Native",
    "NS-3",
    "OAI",
    "VoIP",
    "SDN",
    "NFV",
    "Kubernetes",
    "Wireshark",
    "Radio Planning",
    "Python",
    "MEC",
    "OpenStack",
  ],
  Biotechnology: [
    "Cell Culture",
    "NGS",
    "CRISPR",
    "Python",
    "Bioprocessing",
    "Flow Cytometry",
    "qPCR",
    "DOE",
    "ELISA",
    "Protein Purification",
    "SPC",
    "Bioinformatics",
    "Gene Therapy",
    "Clone Selection",
    "Analytical Dev",
  ],
};

const NARRATIVE_TEMPLATES: Record<string, string[]> = {
  Technology: [
    "This resume has been optimized for a {title} role at {company}. The professional summary now opens with a focus on system architecture and technical leadership, reflecting the company's emphasis on scalable infrastructure. The skills section has been reorganized to prioritize the exact tech stack mentioned in the job description, and project descriptions now include specific keywords like 'microservices' and 'CI/CD' that the company's ATS is likely scanning for.",
    "Tailored for {company}'s {title} position, this version highlights full-stack development experience with emphasis on the specific frameworks the team uses. The summary was rewritten to stress cross-functional collaboration and agile methodologies, which are core to {company}'s engineering culture. Added measurable outcomes (performance improvements, user adoption) to each project bullet.",
    "For this {title} application at {company}, the resume emphasizes machine learning pipeline experience and data-driven decision making. The skills section was reordered to lead with Python, TensorFlow, and cloud ML services. Experience bullets were rewritten to highlight end-to-end ML project ownership and deployment at scale.",
  ],
  Healthcare: [
    "This resume has been tailored for a {title} role at {company}, emphasizing the intersection of clinical domain knowledge and technical expertise. The summary now leads with patient-centered data analysis experience, and the skills section prioritizes HL7, FHIR, and regulatory compliance. Project descriptions now highlight measurable improvements in patient outcomes and data quality.",
    "Optimized for {company}'s healthcare analytics team, this version showcases experience with EHR interoperability and clinical decision support systems. The narrative now connects technical skills directly to healthcare delivery improvements, with specific examples of how data analysis reduced readmissions or improved diagnostics.",
    "For this {title} position at {company}, the resume highlights biostatistics and epidemiological research experience. The education section now includes relevant coursework in clinical trial design and health informatics. Skills were reordered to prioritize statistical tools (R, SAS) and clinical data standards.",
  ],
  Finance: [
    "Tailored for a quantitative role at {company}, this resume emphasizes mathematical modeling, risk analysis, and programming expertise. The summary now opens with a focus on data-driven financial decision making. The skills section leads with Python, R, and SQL, followed by Bloomberg Terminal and Excel VBA. Experience bullets now include specific metrics around portfolio performance and risk-adjusted returns.",
    "This version targets {company}'s fintech engineering team, highlighting experience building trading infrastructure and financial data pipelines. The narrative connects software engineering skills to financial domain expertise, with project descriptions emphasizing low-latency systems and regulatory compliance.",
    "For this {title} role at {company}, the resume emphasizes credit risk modeling and regulatory compliance experience. The skills section was reorganized to prioritize statistical modeling tools and risk frameworks. Added specific examples of model development and validation work with quantified business impact.",
  ],
  Energy: [
    "This resume has been tailored for a renewable energy role at {company}, emphasizing sustainability expertise and technical analysis skills. The summary now leads with a passion for clean energy transition and hands-on experience with power system modeling. Skills prioritize MATLAB, Python, and energy-specific software tools.",
    "For {company}'s grid modernization team, this version highlights experience with smart grid technologies and energy storage systems. The narrative connects data analytics expertise to grid optimization outcomes, with project descriptions emphasizing load forecasting and demand response programs.",
    "Optimized for a {title} position at {company}, this resume emphasizes environmental impact analysis and carbon accounting. The experience section now includes specific projects with measurable sustainability outcomes (CO2 reduction, efficiency gains). Added GIS and geospatial analysis skills relevant to site assessment.",
  ],
  Education: [
    "This resume has been tailored for an EdTech role at {company}, emphasizing instructional design expertise and learning science knowledge. The summary now bridges pedagogical experience with technical skills, highlighting a data-driven approach to improving learner outcomes. Skills prioritize LMS platforms, analytics tools, and accessibility standards.",
    "For {company}'s product team, this version highlights experience designing learning experiences and measuring educational impact. The narrative connects UX research skills to student engagement metrics, with project descriptions emphasizing A/B testing and learning analytics dashboards.",
    "Optimized for a {title} role at {company}, this resume emphasizes curriculum development and assessment design expertise. The experience section now includes specific examples of course design with measurable learning outcomes. Added AI-powered tutoring and adaptive learning technology experience.",
  ],
  Manufacturing: [
    "Tailored for an Industry 4.0 role at {company}, this resume emphasizes automation expertise and data-driven process improvement. The summary now leads with Lean and Six Sigma credentials alongside technical skills. Skills section prioritizes PLC programming, MES systems, and industrial IoT platforms.",
    "For {company}'s operations team, this version highlights experience with predictive maintenance and quality optimization. The narrative connects industrial engineering fundamentals to digital transformation outcomes, with project descriptions emphasizing OEE improvements and defect reduction.",
    "Optimized for a {title} position at {company}, this resume emphasizes supply chain analytics and production planning. The experience section now includes specific process improvement projects with quantified cost savings and efficiency gains. Added ERP systems expertise and cross-functional team leadership examples.",
  ],
  Retail: [
    "This resume has been tailored for an analytics role at {company}, emphasizing customer insights and demand forecasting expertise. The summary now leads with a track record of driving revenue through data-driven merchandising decisions. Skills prioritize SQL, Python, and retail analytics platforms.",
    "For {company}'s omnichannel team, this version highlights experience with personalization engines and inventory optimization. The narrative connects data science skills to customer experience improvements, with project descriptions emphasizing recommendation systems and price optimization algorithms.",
    "Optimized for a {title} role at {company}, this resume emphasizes e-commerce analytics and digital marketing expertise. The experience section now includes specific examples of A/B testing and growth experiments with measurable conversion improvements. Added supply chain and logistics optimization experience.",
  ],
  Government: [
    "This resume has been tailored for a public sector role at {company}, emphasizing policy analysis and program evaluation expertise. The summary now leads with a commitment to mission-driven work and a track record of delivering public value through data-informed decisions. Skills prioritize data visualization, GIS, and stakeholder engagement.",
    "For {company}'s digital services team, this version highlights experience with civic tech and open data initiatives. The narrative connects technical skills to public service outcomes, with project descriptions emphasizing transparency, accessibility, and constituent engagement improvements.",
    "Optimized for a {title} position at {company}, this resume emphasizes cybersecurity and risk management expertise relevant to federal systems. The experience section now includes specific examples of security assessments and compliance audits. Added knowledge of NIST frameworks and federal acquisition regulations.",
  ],
  Consulting: [
    "Tailored for a strategy role at {company}, this resume emphasizes problem-solving frameworks and client impact. The summary now leads with a track record of delivering measurable business outcomes across industries. Skills prioritize financial modeling, data analysis, and executive communication.",
    "For {company}'s technology practice, this version highlights digital transformation and change management experience. The narrative connects technical expertise to business strategy, with project descriptions emphasizing cloud migrations, agile transformations, and operational efficiency gains.",
    "Optimized for a {title} role at {company}, this resume emphasizes data analytics and data storytelling expertise. The experience section now includes specific client engagement examples with quantified impact (revenue growth, cost reduction). Added cross-industry expertise and stakeholder management skills.",
  ],
  Media: [
    "This resume has been tailored for a content analytics role at {company}, emphasizing audience development and monetization expertise. The summary now leads with a track record of growing engaged audiences through data-informed content strategies. Skills prioritize streaming analytics, A/B testing, and ad tech platforms.",
    "For {company}'s product engineering team, this version highlights experience with recommendation systems and real-time streaming infrastructure. The narrative connects software engineering skills to viewer engagement metrics, with project descriptions emphasizing latency reduction and personalization quality improvements.",
    "Optimized for a {title} position at {company}, this resume emphasizes digital content strategy and distribution analytics. The experience section now includes specific examples of content performance optimization with measurable reach and engagement improvements. Added programmatic advertising and yield management experience.",
  ],
  Automotive: [
    "Tailored for an EV engineering role at {company}, this resume emphasizes battery technology and power electronics expertise. The summary now leads with a passion for sustainable transportation and hands-on experience with electric drivetrain development. Skills prioritize MATLAB, embedded systems, and functional safety standards.",
    "For {company}'s autonomous driving team, this version highlights experience with ADAS systems and sensor fusion. The narrative connects software and controls expertise to vehicle safety outcomes, with project descriptions emphasizing perception algorithms and validation testing.",
    "Optimized for a {title} position at {company}, this resume emphasizes manufacturing engineering and quality systems. The experience section now includes specific process improvement projects with quantified defect reduction and efficiency gains. Added ISO 26262 functional safety and ASPICE process knowledge.",
  ],
  Pharmaceuticals: [
    "This resume has been tailored for a CMC role at {company}, emphasizing process development and analytical expertise. The summary now leads with a track record of advancing molecules from late-stage development to commercial launch. Skills prioritize GMP compliance, method validation, and statistical analysis.",
    "For {company}'s clinical operations team, this version highlights experience with trial management and regulatory submissions. The narrative connects scientific expertise to operational efficiency, with project descriptions emphasizing patient recruitment, data quality, and timeline adherence.",
    "Optimized for a {title} position at {company}, this resume emphasizes quality assurance and validation expertise. The experience section now includes specific examples of method transfer and cleaning validation with measurable right-first-time rates. Added ICH guideline knowledge and regulatory inspection readiness experience.",
  ],
  Aerospace: [
    "Tailored for a spacecraft engineering role at {company}, this resume emphasizes systems engineering and mission design expertise. The summary now leads with a passion for space exploration and hands-on experience with satellite development. Skills prioritize STK, MATLAB, C++, and model-based systems engineering.",
    "For {company}'s GNC team, this version highlights experience with orbital mechanics and flight software. The narrative connects controls engineering expertise to mission success outcomes, with project descriptions emphasizing trajectory optimization and autonomous navigation algorithms.",
    "Optimized for a {title} position at {company}, this resume emphasizes propulsion engineering and thermal analysis. The experience section now includes specific component design projects with quantified performance margins. Added environmental testing (TVAC, vibration) and requirements management (DOORS) experience.",
  ],
  Telecommunications: [
    "This resume has been tailored for a 5G systems role at {company}, emphasizing radio access network and core network expertise. The summary now leads with a track record of optimizing network performance and capacity. Skills prioritize 5G NR, Python, network simulation tools, and cloud-native architectures.",
    "For {company}'s network engineering team, this version highlights experience with VoIP and real-time communications. The narrative connects protocol-level expertise to quality of service outcomes, with project descriptions emphasizing latency reduction and call quality improvements.",
    "Optimized for a {title} position at {company}, this resume emphasizes cloud infrastructure and edge computing for telecom. The experience section now includes specific examples of CNF deployment and network slicing implementations. Added automation and orchestration (Kubernetes, ONAP) experience.",
  ],
  Biotechnology: [
    "Tailored for a gene therapy role at {company}, this resume emphasizes cell engineering and viral vector expertise. The summary now leads with a passion for developing transformative therapies and hands-on experience with AAV and lentiviral platforms. Skills prioritize cell culture, molecular biology, and analytical techniques.",
    "For {company}'s process development team, this version highlights experience with upstream and downstream bioprocessing. The narrative connects bench-scale expertise to manufacturing readiness, with project descriptions emphasizing yield improvement and process robustness.",
    "Optimized for a {title} position at {company}, this resume emphasizes analytical development and quality control. The experience section now includes specific assay development and validation projects with measurable precision and accuracy metrics. Added regulatory CMC writing and DOE/statistical analysis experience.",
  ],
};

function getRandomItems<T>(arr: T[], count: number): T[] {
  const shuffled = [...arr].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

function generateDate(baseDate: Date, offsetDays: number): string {
  const d = new Date(baseDate);
  d.setDate(d.getDate() - offsetDays);
  return d.toISOString().split("T")[0]!;
}

export interface MockTailoredResume {
  job: Job;
  resume: TailoredResume;
  highlights: string[];
  changesMade: string[];
  narrativeSummary: string;
  keywordsMatched: string[];
  keywordsMissing: string[];
}

export function generateMockResumes(
  profileId: number = 1,
  count: number = 100
): MockTailoredResume[] {
  const baseDate = new Date("2026-04-20");
  const results: MockTailoredResume[] = [];

  for (let i = 0; i < count; i++) {
    const sector = SECTORS[i % SECTORS.length];
    const companies = COMPANIES[sector] ?? COMPANIES["Technology"];
    const company = companies[i % companies.length];
    const titles = JOB_TITLES[sector] ?? JOB_TITLES["Technology"];
    const title = titles[i % titles.length];
    const fitScore = Math.floor(Math.random() * 41) + 55; // 55-95
    const deadlineOffset = Math.floor(Math.random() * 60) + 7;
    const createdOffset = Math.floor(Math.random() * 30);

    const job: Job = {
      id: i + 1,
      profileId,
      sectorId: (i % SECTORS.length) + 1,
      title,
      company,
      location: [
        "New York, NY",
        "San Francisco, CA",
        "Seattle, WA",
        "Austin, TX",
        "Boston, MA",
        "Chicago, IL",
        "Denver, CO",
        "Los Angeles, CA",
        "Remote",
        "Washington, DC",
        "Atlanta, GA",
        "Raleigh, NC",
        "San Diego, CA",
        "Minneapolis, MN",
        "Portland, OR",
      ][i % 15],
      jobDescription: `We are seeking a talented ${title} to join our ${sector} team at ${company}. The ideal candidate will have strong technical skills, excellent communication abilities, and a passion for innovation. You will work on challenging projects that impact millions of users and collaborate with cross-functional teams to deliver exceptional results.`,
      requirements: `Bachelor's degree in a relevant field. 3-5 years of experience in ${sector.toLowerCase()}. Proficiency with modern tools and technologies. Strong problem-solving skills. Ability to work independently and as part of a team.`,
      responsibilities: `Design and implement solutions for complex ${sector.toLowerCase()} challenges. Collaborate with stakeholders to define requirements and deliverables. Analyze data and present findings to senior leadership. Mentor junior team members and contribute to a culture of continuous learning.`,
      salaryRange: [
        "$80,000 - $120,000",
        "$90,000 - $140,000",
        "$100,000 - $150,000",
        "$110,000 - $160,000",
        "$120,000 - $180,000",
        "$130,000 - $200,000",
        "$140,000 - $220,000",
        "$150,000 - $250,000",
      ][i % 8],
      jobType: ["Full-time", "Contract", "Hybrid"][i % 3],
      experienceLevel: ["Entry", "Mid", "Senior"][i % 3],
      applicationLink: "#",
      deadline: generateDate(baseDate, -deadlineOffset),
      postedDate: generateDate(baseDate, -(deadlineOffset + 14)),
      source: ["LinkedIn", "Indeed", "Company Site", "Glassdoor"][i % 4],
      fitScore,
      matchReasons: `Strong match based on skills alignment, experience level, and career trajectory.`,
      skillGaps: `Minor gaps in domain-specific tooling that can be addressed through onboarding.`,
      status: "discovered",
      createdAt: new Date(baseDate.getTime() - createdOffset * 24 * 60 * 60 * 1000),
    };

    const sectorHighlights = HIGHLIGHT_TEMPLATES[sector] ?? HIGHLIGHT_TEMPLATES["Technology"];
    const highlights = getRandomItems(sectorHighlights, 3);

    const sectorChanges = CHANGE_TEMPLATES[sector] ?? CHANGE_TEMPLATES["Technology"];
    const changesMade = getRandomItems(sectorChanges, 5);

    const sectorKeywords = KEYWORDS[sector] ?? KEYWORDS["Technology"];
    const matchedCount = Math.floor(Math.random() * 5) + 8;
    const keywordsMatched = getRandomItems(sectorKeywords, matchedCount);
    const keywordsMissing = getRandomItems(
      sectorKeywords.filter((k) => !keywordsMatched.includes(k)),
      Math.min(3, sectorKeywords.length - matchedCount)
    );

    const sectorNarratives = NARRATIVE_TEMPLATES[sector] ?? NARRATIVE_TEMPLATES["Technology"];
    const narrativeTemplate = sectorNarratives[i % sectorNarratives.length];
    const narrativeSummary = narrativeTemplate
      .replace(/{title}/g, title)
      .replace(/{company}/g, company);

    const resume: TailoredResume = {
      id: i + 1,
      jobId: job.id,
      profileId,
      content: JSON.stringify({
        title,
        company,
        sector,
        fitScore,
        highlights,
        changesMade,
        narrativeSummary,
        keywordsMatched,
        keywordsMissing,
      }),
      pdfUrl: null,
      highlights: JSON.stringify(highlights),
      changesMade: JSON.stringify(changesMade),
      narrativeSummary,
      createdAt: job.createdAt,
    };

    results.push({
      job,
      resume,
      highlights,
      changesMade,
      narrativeSummary,
      keywordsMatched,
      keywordsMissing,
    });
  }

  return results;
}
